### ISSUE TITLE
rename "weights" in PosteriorCollection.sample to "ratios"

### ISSUE THREAD

**Issue by bkmi** [undark-lab/swyft#14]
Why would we call it anything else?

**Comment by cweniger** [comment]
In the context of nested sampling, these quantities are called "weights" (since they are the weights of weighted samples). It is right that in our case they correspond to posterior/prior ratios, but that describes their origin, not their purpose.

**Comment by bkmi** [comment]
I would argue they should be called ratios in nested sampling.

Weights is super general. It's not a big enough point to fuss about.

**Comment by cweniger** [comment]
Sorry for reopening, but I think it is worth discussion (even if on the side). Another somewhat wild option would be to directly link the meaning of these quantities to https://en.wikipedia.org/wiki/Pointwise_mutual_information maybe something like "pmi", but not sure if this would really be of any help.

I think terminology matters since it helps to drive intuition. We can vote about this and other points (e.g. "focus", "microscope", etc.) before the next realase, taking also into account votes from eScience.
