### ISSUE TITLE
reduce number of dictionaries returned, replaced with dataclasses

### ISSUE THREAD

**Issue by bkmi** [undark-lab/swyft#15]
**Why?** 

1. As a user, you have to know the names of the keys to be able to access the data. This is annoying when you're writing code, especially in a non-interactive setting.

2. As a code designer, we already know what should be in the dictionary. If there is nothing dynamic about the keys, we should handle it.

**Where?**
I will have to put together a list of objects which would be useful to do this. The first thing that comes to mind are the returned samples with `params` and `weights`. This comes up throughout the code though

**Comment by cweniger** [comment]
I'm all for simplifying, but the weights will have dynamic keys which represent the various marginals. For inspiration, you can have a look at https://arviz-devs.github.io/arviz/. It reads all kinds of sampling input formats, and making swyft compatible with one of those would enable us to use arviz for making the plots, instead of or in additional to our custom routines.

**Comment by bkmi** [comment]
I imagine

```>>>type(posterior.params)
np.ndarray```

```>>>type(posterior.weights)
Dict[Tuple, np.ndarray]```
