### ISSUE TITLE
use array_to_tensor everywhere

### ISSUE THREAD

**Issue by bkmi** [undark-lab/swyft#7]
Right now, everything in our code forces the use of float32. This may not be appealing for some users, and is, in general, bad practice.

If we made more use of torch builtins, instead of numpy, including this change would allow us to generate some tensors directly on the gpu.

--

Update: The goal here is to allow pytorch standard use of device and dtype.

**Comment by cweniger** [comment]
It might be best to become completely independent of default types in torch, in order to avoid collisions with other software (for instance clipppy relies on default types, and we might want to have different defaults for clipppy and swyft). I'm still not completely clear about what is the best strategy here.

**Comment by bkmi** [comment]
I'm going to call this good enough for now.
